# Generates an operator-facing README.md in every Ember add-on configuration folder.
# The detailed feature descriptions live in docs/features/*.json; keep those JSON files as the
# single source of truth and rerun this script after documentation changes.

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ServerRoot
)

$ErrorActionPreference = "Stop"
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}

$repoRoot = Split-Path -Parent $PSScriptRoot
$docsRoot = Join-Path $repoRoot "docs\features"
$resolvedServerRoot = [System.IO.Path]::GetFullPath($ServerRoot)
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$guides = @(
    @{ Folder = "auth";         Title = "Authentication"; Sources = @("auth") }
    @{ Folder = "blocks";       Title = "Custom Blocks"; Sources = @("custom_block") }
    @{ Folder = "economy";      Title = "Economy"; Sources = @("economy"); QuickStart = @(
        'Configure MySQL in economy/economy.toml and set enabled = true.'
        'Give money: `/eco give <player> <amount> [currency]`, for example `/eco give Steve 1000 coins`.'
        'Check balances with `/balance`; transfer money with `/pay <player> <amount> [currency]`.'
    ) }
    @{ Folder = "furniture";    Title = "Furniture"; Sources = @("furniture") }
    @{ Folder = "home";         Title = "Homes"; Sources = @("home") }
    @{ Folder = "hud";          Title = "HUD"; Sources = @("hud") }
    @{ Folder = "menu";         Title = "Menus"; Sources = @("menu") }
    @{ Folder = "npc";          Title = "NPC"; Sources = @("npc"); QuickStart = @(
        'Join the game with OP level 3 and stand where the NPC should appear.'
        'Run `/npc create <name>`, for example `/npc create shopkeeper`.'
        'Set a safe test action with `/npc setaction shopkeeper say Hello %player%`. NPC actions run with console privileges.'
    ) }
    @{ Folder = "physics";      Title = "Physics"; Sources = @("physics") }
    @{ Folder = "resourcepack"; Title = "Resource Pack and Custom Items"; Sources = @("resourcepack", "custom_item") }
    @{ Folder = "shop";         Title = "Shop and Economy Add-ons"; Sources = @("shop", "bank", "market", "lottery") }
)

function Add-FeatureSection {
    param(
        [System.Collections.Generic.List[string]]$Lines,
        [pscustomobject]$Document,
        [string]$Heading,
        [bool]$Combined
    )

    if ($Combined) {
        $Lines.Add("## Component: $Heading")
        $Lines.Add("")
    }

    $Lines.Add([string]$Document.summary)
    $Lines.Add("")

    if ($Document.commands -and $Document.commands.Count -gt 0) {
        $Lines.Add($(if ($Combined) { "### Commands" } else { "## Commands" }))
        $Lines.Add("")
        foreach ($command in $Document.commands) {
            $Lines.Add("- ``$($command.usage)``")
            $Lines.Add("")
            $Lines.Add("  $($command.description)")
            $Lines.Add("")
            $Lines.Add("  Permission: $($command.permission)")
            $Lines.Add("")
        }
    }

    if ($Document.config_files -and $Document.config_files.Count -gt 0) {
        $Lines.Add($(if ($Combined) { "### Configuration and data files" } else { "## Configuration and data files" }))
        $Lines.Add("")
        foreach ($configFile in $Document.config_files) {
            $Lines.Add("- $configFile")
            $Lines.Add("")
        }
    }

    if ($Document.notes -and $Document.notes.Count -gt 0) {
        $Lines.Add($(if ($Combined) { "### Important notes" } else { "## Important notes" }))
        $Lines.Add("")
        foreach ($note in $Document.notes) {
            $Lines.Add("- $note")
            $Lines.Add("")
        }
    }
}

foreach ($guide in $guides) {
    $destinationDirectory = Join-Path $resolvedServerRoot $guide.Folder
    New-Item -ItemType Directory -Path $destinationDirectory -Force | Out-Null

    $sourceNames = @($guide.Sources)
    $sourcePaths = foreach ($sourceName in $sourceNames) {
        $path = Join-Path $docsRoot "$sourceName.json"
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
            throw "Feature documentation source is missing: $path"
        }
        $path
    }

    $lines = New-Object 'System.Collections.Generic.List[string]'
    $lines.Add("# Ember $($guide.Title) Guide")
    $lines.Add("")
    $lines.Add("> Generated by ``scripts/sync-feature-guides.ps1`` from ``docs/features/*.json``. Edit the source JSON and regenerate this file.")
    $lines.Add("")

    if ($guide.QuickStart) {
        $lines.Add("## Quick start")
        $lines.Add("")
        $step = 1
        foreach ($quickStartLine in $guide.QuickStart) {
            $lines.Add("$step. $quickStartLine")
            $lines.Add("")
            $step++
        }
    }

    $combined = $sourcePaths.Count -gt 1
    foreach ($sourcePath in $sourcePaths) {
        $document = Get-Content -LiteralPath $sourcePath -Raw -Encoding UTF8 | ConvertFrom-Json
        Add-FeatureSection -Lines $lines -Document $document -Heading $document.feature -Combined $combined
    }

    $lines.Add("## Documentation sources")
    $lines.Add("")
    foreach ($sourceName in $sourceNames) {
        $lines.Add("- ``docs/features/$sourceName.json``")
    }
    $lines.Add("")

    $destination = Join-Path $destinationDirectory "README.md"
    [System.IO.File]::WriteAllText($destination, ($lines -join [Environment]::NewLine), $utf8NoBom)
    Write-Host "[generated] $destination" -ForegroundColor Green
}

Write-Host "Generated $($guides.Count) feature guides." -ForegroundColor Cyan
